// Geocoding, forgiving street-name suggestions, and OSRM road/footpath routing.
// All network calls hit the same free OSM services as the original viewer:
// Nominatim (geocode), Overpass (street-name fallback), OSRM demo (geometry).
import { deburr, lev } from './util.js';
import STREETS from './data/streets.json';

/** Concise human label from a Nominatim result. */
export function geoLabel(x) {
	const a = x.address || {};
	const road = a.road || a.pedestrian || a.footway || a.neighbourhood || '';
	const num = a.house_number ? ' ' + a.house_number : '';
	const area = a.suburb || a.city_district || a.village || a.town || a.city || '';
	const main = (road + num).trim();
	if (main) return area && area !== main ? `${main}, ${area}` : main;
	return x.display_name.split(',').slice(0, 2).join(',').trim();
}

// Geocode against OSM Nominatim. viewbox biases (not bounds) toward the city,
// the city is auto-appended for context, and if nothing matches we retry
// without a trailing house number (OSM often lacks house-level data here).
export async function geocode(q) {
	const base =
		'https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1' +
		'&limit=5&countrycodes=hr&viewbox=17.90,45.25,18.15,45.10&q=';
	const hit = async (query) => {
		const r = await fetch(base + encodeURIComponent(query), {
			headers: { Accept: 'application/json' }
		});
		return r.ok ? r.json() : [];
	};
	const withCity = /brod/i.test(q) ? q : q + ', Slavonski Brod';
	let res = await hit(withCity);
	if (!res.length) {
		const noNum = q.replace(/\s+\d+[a-z]?$/i, '').trim(); // drop trailing house no.
		if (noNum && noNum !== q) res = await hit(noNum + ', Slavonski Brod');
	}
	return res.map((x) => ({ lat: +x.lat, lon: +x.lon, label: geoLabel(x) }));
}

// City street names ship baked in data/streets.json (regenerated by
// scripts/build_streets.sh) so suggestions are instant and work offline.
// Overpass is only a fallback if that list is somehow empty, cached 30 days.
const STREETS_KEY = 'sb_streets';
const STREETS_TTL = 30 * 864e5;
let streetNames = Array.isArray(STREETS) && STREETS.length ? STREETS : null;
let streetFetch = null;

function loadStreets() {
	if (streetNames) return Promise.resolve(streetNames);
	if (streetFetch) return streetFetch;
	try {
		const c = JSON.parse(localStorage.getItem(STREETS_KEY) || 'null');
		if (c && Date.now() - c.ts < STREETS_TTL && Array.isArray(c.names)) {
			return Promise.resolve((streetNames = c.names));
		}
	} catch {
		/* fall through to fetch */
	}
	const ql =
		'[out:json][timeout:25];area[name="Slavonski Brod"][admin_level~"8|9|10"]->.a;' +
		'way[highway][name](area.a);out tags;';
	streetFetch = fetch('https://overpass-api.de/api/interpreter', {
		method: 'POST',
		headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
		body: 'data=' + encodeURIComponent(ql)
	})
		.then((r) => r.json())
		.then((d) => {
			const names = [
				...new Set((d.elements || []).map((e) => e.tags && e.tags.name).filter(Boolean))
			];
			try {
				localStorage.setItem(STREETS_KEY, JSON.stringify({ ts: Date.now(), names }));
			} catch {
				/* quota */
			}
			return (streetNames = names);
		})
		.catch(() => (streetNames = []));
	return streetFetch;
}

// Closest street names to the typed query (house number stripped), scored by
// each query token's best normalised edit distance to a name token — so a
// one-letter slip or a missing diacritic still matches.
export async function streetSuggestions(q) {
	const names = await loadStreets();
	if (!names || !names.length) return [];
	const qTokens = deburr(q.replace(/\s+\d+[a-z]?$/i, ''))
		.split(/\s+/)
		.filter((t) => t.length > 2);
	if (!qTokens.length) return [];
	return names
		.map((name) => {
			const nTokens = deburr(name).split(/\s+/);
			let sum = 0;
			for (const qt of qTokens) {
				let best = Infinity;
				for (const nt of nTokens) best = Math.min(best, lev(qt, nt) / Math.max(qt.length, nt.length));
				sum += best;
			}
			return { name, score: sum / qTokens.length };
		})
		.filter((s) => s.score <= 0.34)
		.sort((a, b) => a.score - b.score)
		.slice(0, 4)
		.map((s) => s.name);
}

// Road/footpath routing via the public OSRM demo. Used for walk legs ("foot")
// and to fill untraced bus hops ("driving"). Cached (promise per profile +
// rounded endpoint pair); on any failure the straight line drawn first stays.
const osrmCache = {};
export function osrmGeom(profile, a, b) {
	// a, b = [lat, lon]
	const key = `${profile}:${a[0].toFixed(5)},${a[1].toFixed(5)};${b[0].toFixed(5)},${b[1].toFixed(5)}`;
	if (key in osrmCache) return osrmCache[key];
	const url =
		`https://router.project-osrm.org/route/v1/${profile}/` +
		`${a[1]},${a[0]};${b[1]},${b[0]}?overview=full&geometries=geojson`;
	const p = fetch(url)
		.then((r) => (r.ok ? r.json() : null))
		.then((d) => {
			if (!d || d.code !== 'Ok' || !d.routes || !d.routes.length) return null;
			return d.routes[0].geometry.coordinates.map(([lon, lat]) => [lat, lon]);
		})
		.catch(() => null);
	osrmCache[key] = p;
	return p;
}

export const walkRoute = (a, b) => osrmGeom('foot', a, b);
